include(
    ":app",
    ":libraries:core",
    ":libraries:data",
    ":libraries:domain",
    ":libraries:test-utils",
    ":features:home",
    ":features:post_detail",
    ":features:search",
    ":features:dashboard",
    ":features:notification",
    ":features:account"
)
