include(
    ":app",
    ":libraries:core",
    ":libraries:data",
    ":libraries:domain",
    ":libraries:test-utils",
    ":features:post_detail",
    ":features:search",
    ":features:dashboard"
)
